### ISSUE TITLE
[fix] LinkItem UI 개선

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#125]
## 📌 Feature Issues
1. 둘러보기에 스크롤이 생기는 부분
2. url, desc 부분이 ...으로 생략이 되지않는 부분
3. 썸네일 이미지가 각각 다른 부분

## ✨ To-do

- [x] overflow 제거
- [x] desc 3줄이 넘어가면 생략
- [x] desc 없다면 height 생략
- [x] 이미지를 일괄적으로 100%로 바꿈
