### ISSUE TITLE
[test] 테스트코드 셋업

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#188]
## 📌 Feature Issues
프로젝트 테스트 코드 기본 셋업

## ✨ To-do
- [x] jest.config.js 설정
- [x] package.json script 작성
- [x] redux provider 테스트 환경 구축
