### ISSUE TITLE
[test] 프로필 페이지 테스트 코드 작성

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#191]
## 📌 Feature Issues
프로필 페이지 테스트 코드 작성할게요

## ✨ To-do
- [x] 화면에 텍스트, 이미지, 버튼이 렌더링 되는지
- [x] 이미지 변경 동작하는지
- [x] 수정버튼 누르면 프로필 업데이트 api호출되는지
