### ISSUE TITLE
[fix] nickname -> userId, pk변경

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#202]
## 📌 Feature Issues
pk로 유지중인 nickname을 userId로 변경해요

## ✨ To-do
- [ ] 프로필 클릭시 url, /nickname으로 유지하면서 /userId로 통신하기
- [ ] userId number로 타입변환
- [ ] api통신에 모든 nickname -> userId로 변경

백엔드 운영서버 증설 완료 후 merge예정
