### ISSUE TITLE
[feat] 해시태그 컴포넌트 개선

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#243]
## 📌 Feature Issues
흩어져있는 해시태그 컴포넌트를 합치는 작업

## ✨ To-do
- [x] 디자인에 따른 해시태그 분리
- [x] baseTag를 중심으로 확장하기
- [x] 불필요한 해시태그 삭제
- [x] 해시태그를 받는 리스트는 1개로 줄이기
- [x] 해시태그는 props로 로직 받기
