### ISSUE TITLE
[fix] 현재 기능에서 보이는 버그

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#262]
## 📌 Feature Issues
요청들어온 버그를 우선적으로 해결할게요

## ✨ To-do
- [ ] 최초 로그인 시 둘러보기 기능 제한
- [ ] 서비스 배경 색 조절 (스크롤 길어질 때 배경색이 사라짐)
- [ ] 마크 후 바로 반영안되는 문제
- [ ] 스크롤 끝까지 안되는 이슈
