### ISSUE TITLE
[feat] 리덕스 환경세팅

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#34]
## 📌 Feature Issues
리덕스 툴킷으로 해볼게요(처음써봄..)

## ✨ To-do
- [x] 필요한 라이브러리 설치
- [x] 폴더 구조 세팅
- [x] 기초 코드 작성
