### ISSUE TITLE
[feat] customAPI 개선

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#55]
## 📌 Feature Issues
기존 axiosInstance에 auth, formData등 추가해야할 인스턴스가 생겼고 반복되는 부분이 발생했어요

## ✨ To-do
- [x] 디버그를 담당하는 interceptor를 분리
- [x] instance를 생성하는 부분을 분리
- [x] 바뀌는 부분인 headers를 인자로 변경
