### ISSUE TITLE
[feat] https:localhost:3000으로 포트 열기

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#61]
## 📌 Feature Issues
http => https로 localhost를 열어서 api서버와 https를 맞춰요

## ✨ To-do
- [x] server.js 파일생성
- [x] script 수정
- [x] ssl 키 루트 디렉토리에 발급
- [x] init-https 자동화
