### ISSUE TITLE
[feat] 로그인후 Nickname을 넣어서 사용자 회원가입

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#83]
## 📌 Feature Issues
소셜 로그인 후 Nickname을 입력하는 페이지 or 팝업창을 만들어야함

## ✨ To-do
- [x] UI 작업
- [x] nickname을 수정하는 (default : 빈 문자열) api함수를 구현
- [x] 조건에 따라 message 색상 변경 & 체크, x, spinner SVG 렌더링
- [x] API호출 제한을 위한 Debounce 구현
- [x] 로그인 후 최초 로그인인지 판단 후 nickname을 입력하는 페이지 or 팝업창을 띄워줘야함
